# Generated by Django 4.1.4 on 2022-12-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('salary', models.PositiveSmallIntegerField(default=0, verbose_name='Заработная плата')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Преимущества')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date_applying', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отзыва')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('cv', models.FileField(blank=True, null=True, upload_to='', verbose_name='Резюме')),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
