# Generated by Django 4.1.4 on 2022-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applying_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applying',
            options={'verbose_name': 'Отклики', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение для вакансии'),
        ),
        migrations.AlterField(
            model_name='applying',
            name='date_applying',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отклика'),
        ),
    ]
