# Generated by Django 4.1.4 on 2022-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vacancy_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='birthday',
            field=models.CharField(default='', max_length=15, verbose_name='День рождения'),
        ),
    ]
