# Generated by Django 4.1.4 on 2022-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_applying_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='email',
            field=models.EmailField(default='e@na.ru', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
