# Generated by Django 4.1.4 on 2022-12-19 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_applying_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Резюме'),
        ),
    ]
