# Generated by Django 4.1.4 on 2022-12-19 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_applying_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applying/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'doc', 'docx', 'xlsx'])], verbose_name='Резюме'),
        ),
    ]
